# Generated by Django 5.1.15 on 2026-07-09 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0005_param_audit_finalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('padding', models.PositiveSmallIntegerField(default=5)),
                ('period', models.CharField(choices=[('NONE', 'Continuous'), ('YEAR', 'Resets yearly'), ('MONTH', 'Resets monthly')], default='NONE', max_length=8)),
                ('period_key', models.CharField(blank=True, default='', max_length=10)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.company')),
            ],
            options={
                'db_table': 'core_document_sequence',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code', 'period_key'), name='uq_docseq_tenant_code_period')],
            },
        ),
    ]
