# Generated by Django 5.1.15 on 2026-07-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'mst_company',
            },
        ),
        migrations.CreateModel(
            name='ParameterType',
            fields=[
                ('id', models.AutoField(db_column='ParameterType_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ParameterTypeName', max_length=100)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, db_column='EntryDate', null=True)),
                ('entry_by', models.IntegerField(blank=True, db_column='EntryBy', null=True)),
                ('entry_ip', models.CharField(blank=True, db_column='EntryIP', max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('update_by', models.IntegerField(blank=True, db_column='UpdateBy', null=True)),
                ('update_ip', models.CharField(blank=True, db_column='UpdateIP', max_length=50, null=True)),
            ],
            options={
                'db_table': 'MST_ParameterType',
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.AutoField(db_column='ParameterValue_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ParameterValueName', max_length=500)),
                ('short_name', models.CharField(blank=True, db_column='ShortName', max_length=50, null=True)),
                ('sequence_no', models.IntegerField(blank=True, db_column='SequenceNo', null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=500, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, db_column='EntryDate', null=True)),
                ('entry_by', models.IntegerField(blank=True, db_column='EntryBy', null=True)),
                ('entry_ip', models.CharField(blank=True, db_column='EntryIP', max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, db_column='UpdateDate', null=True)),
                ('update_by', models.IntegerField(blank=True, db_column='UpdateBy', null=True)),
                ('update_ip', models.CharField(blank=True, db_column='UpdateIP', max_length=50, null=True)),
                ('parameter_type', models.ForeignKey(db_column='ParameterType_Id', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='masters.parametertype')),
            ],
            options={
                'db_table': 'MST_ParameterValue',
                'ordering': ['sequence_no', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mst_system_setting',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'key'), name='uq_setting_tenant_key')],
            },
        ),
    ]
