# Generated by Django 5.1.15 on 2026-07-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'acc_module_group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'acc_user_role',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('route', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('module_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='access.modulegroup')),
            ],
            options={
                'db_table': 'acc_form',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'acc_role',
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='uq_role_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='RoleFormPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.form')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_permissions', to='access.role')),
            ],
            options={
                'db_table': 'acc_role_form_permission',
            },
        ),
        migrations.CreateModel(
            name='UserFormPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_save', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='access.form')),
            ],
            options={
                'db_table': 'acc_user_form_permission',
            },
        ),
    ]
