# Generated by Django 5.1.15 on 2026-07-08 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='access.form')),
            ],
            options={
                'db_table': 'acc_grid_column',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleColumnPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access.gridcolumn')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='access.role')),
            ],
            options={
                'db_table': 'acc_role_column_permission',
            },
        ),
        migrations.CreateModel(
            name='UserColumnPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='access.gridcolumn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acc_user_column_permission',
            },
        ),
        migrations.AddConstraint(
            model_name='gridcolumn',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='uq_grid_column_form_key'),
        ),
        migrations.AddConstraint(
            model_name='rolecolumnpermission',
            constraint=models.UniqueConstraint(fields=('role', 'column'), name='uq_role_column'),
        ),
        migrations.AddConstraint(
            model_name='usercolumnpermission',
            constraint=models.UniqueConstraint(fields=('user', 'column'), name='uq_user_column'),
        ),
    ]
